### ISSUE TITLE
It doesn't work with async function

### ISSUE THREAD

**Issue by liuxh0** [detro/consoleplusplus#19]
```javascript
require("consoleplusplus")

async function foo() {
  JSON.parse(undefined)
}

foo()
```

Running this code, I got the error: 
```
/Users/xliu/tmp/test/node_modules/consoleplusplus/console++.js:301
    if (arguments.length > 0 && this.isLevelVisible(_LEVELS.ERROR)) {
                                     ^

TypeError: this.isLevelVisible is not a function
    at console.error (/Users/xliu/tmp/test/node_modules/consoleplusplus/console++.js:301:38)
    at writeOut (internal/process/warning.js:32:3)
    at process.onWarning (internal/process/warning.js:84:3)
    at process.emit (events.js:315:20)
    at internal/process/warning.js:57:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Well, after removing `async`, I get the expected error:
```
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at foo (/Users/xliu/tmp/test/index.js:4:8)
    at Object.<anonymous> (/Users/xliu/tmp/test/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Although it works when catching the error explicitly, but without stacktrace: 
```javascript
foo().catch(err => {
  console.error(err)
})
```

Any idea why this happens?

**Comment by detro** [comment]
I'm sorry, but as you can see I haven't had any engagement with this module for 5yy.
I have never tested it with more recent versions of NodeJS.

It's such a tiny project, that if you found a fix that would make it work for more recent versions, I'd be happy to review your PR and merge even.

**Comment by liuxh0** [comment]
@detro Thanks for your reply. I will try to work on a PR :-)

**Comment by liuxh0** [comment]
For those who want to solve this temporarily, use this hack:
```javascript
process.on('unhandledRejection', error => {
  throw error;
});
```
